{% set name = "setuptools-parcels" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/setuptools-parcels-{{ version }}.tar.gz
  sha256: 8cebbefb971524ec44ca4f0d23d60d2cd0ffae4295e09031876dd9651144408d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - setuptools_parcels
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/toumorokoshi/setuptools-parcels
  summary: an alternative interface to package_data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
